version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: job-hunter-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jobhunter
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/seed:/docker-entrypoint-initdb.d   # <-- QUAN TRá»ŒNG
    networks:
      - job-hunter-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: job-hunter-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jobhunter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - job-hunter-network

networks:
  job-hunter-network:
    driver: bridge

volumes:
  mysql-data:
